### ISSUE TITLE
1.0.0 release? 

### ISSUE THREAD

**Issue by Datseris** [JuliaStats/MultivariateStats.jl#73]
Hi, what's the plan for a 1.0.0 tag? What is left to be done? In general some stability promise would go a long way for developers like us (JuliaDynamics)

**Comment by Datseris** [comment]
> I do not recall any particular plan for versioning.

I thought the plan for *all accepted* Julia packages was to follow this: https://semver.org/ .

> As for stability, the API haven't changed for years: fit/transform[/reconstruct].

I do not understand. Then what's the problem with releasing a version 1.0.0?

It is important for people depending here. As instructed by SymVer, you can do whatever change you want to a non-major version. If you release 1.0.0, this would allow us safely to depend on versions `[1.0.0, 2.0.0)` without ever having a worry.

As a (very tiny) developer of Julia packages, I don't understand your comment. You can still release a 2.0.0 version if in "years" from now you want to do breaking changes. Please help me understand what "problems" are there in releasing a major version.

**Comment by wildart** [comment]
> Please help me understand what "problems" are there in releasing a major version.

There are no "problems" per se but some outstanding issues.

In my opinion, for a proper long lasted release following issues need to be addressed first:
- [ ] CMDS API inconsistency (related to #60)
- [ ] some type instabilities (#53)
- [ ] a ICA convergence issue (#45).

Of course, documentation and examples need to be straighten up. I like `Documenter.jl` set of features (e.g. doctests) and a unified look.

**Comment by wildart** [comment]
All things done for 1.0.0 release. It will be out shortly.
